name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout Zwavejs2Mqtt
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Lint
        if: matrix['node-version'] == '14.x'
        run: yarn run lint

      - name: Prepare lint auto-fix patch
        if: |
          matrix['node-version'] == '14.x' &&
          failure() &&
          github.event_name == 'pull_request'
        id: lint
        run: |
          # Run all lint commands and abort if one has unfixable errors
          yarn run lint-fix
          git diff --name-only || true
          if ! git diff --quiet ; then
            echo "has changes"
            git diff > fix.patch
            echo "::set-output name=changed::true"
          else
            echo "unchanged"
            echo "::set-output name=changed::false"
          fi
      - name: Upload Patch
        if: |
          matrix['node-version'] == '14.x' &&
          failure() &&
          github.event_name == 'pull_request' &&
          steps.lint.outputs.changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: lint-fix
          path: fix.patch

      - name: Test
        run: yarn run test

      - name: Generate coverage report
        if: matrix['node-version'] == '14.x'
        run: |
          yarn run coverage
          yarn run record-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: matrix['node-version'] == '14.x'
        with:
          github-token: ${{ secrets.github_token }}
